;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        complete
        completion-kill-region
        org-delete-char
        org-end-of-line
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        helm-confirm-and-exit-minibuffer
        ))
